name: FoodComing CICD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Set python path
      run: |
        echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV
        echo "$PYTHONPATH"

    - name: Prepare env variables
      env:
        ENV_TEST_BASE64: ${{ secrets.ENV_TEST }}
        ENV_LOCAL_BASE64: ${{ secrets.ENV_LOCAL }}
      run: |
        set -e
        echo "$ENV_TEST_BASE64" | base64 --decode > .env.test || { echo "Failed to decode .env.test"; exit 1; }
        echo "$ENV_LOCAL_BASE64" | base64 --decode > .env.local || { echo "Failed to decode .env.local"; exit 1; }
        ls -l .env.*
        head -n 5 .env.test
  
    - name: Upload env files as artifact
      uses: actions/upload-artifact@v4
      with:
        name: env-files
        path: |
          .env.test
          .env.local

    - name: Debug workspace path
      run: |
        pwd
        echo "Listing all files under workspace:"
        find . -maxdepth 2 -type f

  test:
    runs-on: ubuntu-latest
    needs: build 

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_PASSWORD: ${{ secrets.SQLALCHEMY_PASSWORD }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - name: Download env file
      uses: actions/download-artifact@v4
      with:
        name: env-files

    - name: Load env variables from .env.test
      run: |
        set -o allexport
        source .env.test
        set +o allexport

    - name: Run tests
      env:
        ENVIRONMENT: test
        FLASK_APP: foodcoming.py
      run: |
        export ENVIRONMENT="$ENVIRONMENT"
        flask test