name: FoodComing CICD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Set python path
      run: |
        echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV
        echo "$PYTHONPATH"

    - name: Run tests
      env:
        FLASK_APP: foodcoming.py
      run: |
        flask test

